/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultComboBoxModel;
import model.jdbcConnection;
import model.Patient;
import model.patientStore;
import java.sql.ResultSet;
import java.sql.Connection;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author ABHI
 */
public class communityJPanel extends javax.swing.JPanel {
        //patientStore patientDb;
    /**
     * Creates new form communityJPanel
     * @param patientstore
     */
    public communityJPanel(patientStore patientstore) {
            initComponents();
            
            //this.patientDb = patientDb;
            jdbcConnection obj = new jdbcConnection();
            ArrayList<String> community = new ArrayList<String>();
            
//            community.
             community = obj.neighborhooddropdown();
            final DefaultComboBoxModel model = new DefaultComboBoxModel(community.toArray());
            communityjComboBox.setModel(model); 
           
           // System.out.println(patientstore.getPatientDb().size());
            
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        communityjComboBox = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        minimumAgejTextField = new javax.swing.JTextField();
        maxiumAgejTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();

        setBackground(new java.awt.Color(0, 204, 255));
        setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        setForeground(new java.awt.Color(0, 204, 255));
        setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N

        communityjComboBox.setBackground(new java.awt.Color(0, 204, 255));
        communityjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        communityjComboBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communityjComboBoxActionPerformed(evt);
            }
        });

        jScrollPane2.setBackground(new java.awt.Color(0, 204, 255));

        jTable2.setBackground(new java.awt.Color(0, 204, 255));
        jTable2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable2.setForeground(new java.awt.Color(51, 51, 51));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insurance Number", " Name", "Sex", "Age", "SystolicPressure", "DiastolicPressure", "Community", "City", "ApartmentNumber"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setShowGrid(true);
        jTable2.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(jTable2);

        minimumAgejTextField.setBackground(new java.awt.Color(0, 204, 255));
        minimumAgejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        minimumAgejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                minimumAgejTextFieldActionPerformed(evt);
            }
        });

        maxiumAgejTextField.setBackground(new java.awt.Color(0, 204, 255));
        maxiumAgejTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        maxiumAgejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                maxiumAgejTextFieldActionPerformed(evt);
            }
        });

        searchjButton.setBackground(new java.awt.Color(0, 204, 255));
        searchjButton.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        jLabel1.setBackground(new java.awt.Color(0, 153, 255));
        jLabel1.setFont(new java.awt.Font("Segoe UI Black", 3, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 0));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("ENCOUNTER HISTORY");

        jLabel2.setBackground(new java.awt.Color(0, 204, 255));
        jLabel2.setText("Minimum Age");

        jLabel3.setBackground(new java.awt.Color(0, 204, 255));
        jLabel3.setText("Maximum Age");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 716, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(160, 160, 160)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 281, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(communityjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(minimumAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel2))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(maxiumAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(searchjButton))
                                    .addComponent(jLabel3))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel2))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(minimumAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(maxiumAgejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(searchjButton))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void communityjComboBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communityjComboBoxActionPerformed
                
            try {
                System.out.println(communityjComboBox.getSelectedItem());
                jdbcConnection obj = new jdbcConnection();
                Connection conn = obj.connect();
                ResultSet ars = obj.communitySearch(communityjComboBox.getSelectedItem().toString(),conn);
                DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
                model.setRowCount(0);
                Object[] row = new Object[9];
                while(ars.next())
                { String[] val = ars.getString("SystolicPressure").split(",");
                for(int i=0;i<val.length;i++)
                { if(Integer.parseInt(val[i])>120)
                { 
                row[0] = ars.getString("InsuranceNumber");
                row[1]  = ars.getString("Name");
                row[2] = ars.getString("Sex");
                row[3] = ars.getString("Age");
                row[4] = ars.getString("SystolicPressure");
                row[5] = ars.getString("DiastolicPressure");
                row[6] = ars.getString("Community");
                row[7] = ars.getString("City");
                row[8] = ars.getString("ApartmentNumber");
                
                 }
                    }
          
//                System.out.println(ars.getString("SystolicPressure"));
//                System.out.println(ars.getString("InsuranceNumber"));
//                System.out.println(ars.getString("Name"));
//                System.out.println(ars.getString("Sex"));
//                System.out.println(ars.getString("Age"));
//                System.out.println(ars.getString("ApartmentNumber"));
//                System.out.println(ars.getString("DiastolicPressure"));
//                System.out.println(ars.getString("Community"));
//                System.out.println(ars.getString("City"));
                model.addRow(row);
                }
                obj.closeConnection(conn);
              
            } catch (SQLException ex) {
                Logger.getLogger(communityJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
           
        
        
        
    }//GEN-LAST:event_communityjComboBoxActionPerformed

    private void minimumAgejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_minimumAgejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_minimumAgejTextFieldActionPerformed

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        try {
            // TODO add your handling code here:
            jdbcConnection obj2 = new jdbcConnection();
            String minimumAge = String.valueOf(Integer.parseInt(minimumAgejTextField.getText())-1);
            String maximumAge = String.valueOf((Integer.parseInt(maxiumAgejTextField.getText()))+1);
            Connection con = obj2.connect();
            
            ResultSet ars = obj2.ageSearch(communityjComboBox.getSelectedItem().toString(),minimumAge,maximumAge,con);
            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
            model.setRowCount(0);
            Object[] row = new Object[9];
            while(ars.next()){

               
                { String[] val = ars.getString("SystolicPressure").split(",");
                for(int i=0;i<val.length;i++)
                { if(Integer.parseInt(val[i])>120)
                { 
                row[0] = ars.getString("InsuranceNumber");
                row[1]  = ars.getString("Name");
                row[2] = ars.getString("Sex");
                row[3] = ars.getString("Age");
                row[4] = ars.getString("SystolicPressure");
                row[5] = ars.getString("DiastolicPressure");
                row[6] = ars.getString("Community");
                row[7] = ars.getString("City");
                row[8] = ars.getString("ApartmentNumber");
                
                 }
                    }
          
//                System.out.println(ars.getString("SystolicPressure"));
//                System.out.println(ars.getString("InsuranceNumber"));
//                System.out.println(ars.getString("Name"));
//                System.out.println(ars.getString("Sex"));
//                System.out.println(ars.getString("Age"));
//                System.out.println(ars.getString("ApartmentNumber"));
//                System.out.println(ars.getString("DiastolicPressure"));
//                System.out.println(ars.getString("Community"));
//                System.out.println(ars.getString("City"));
                model.addRow(row);
                }
//
//            System.out.println(ars.getString("SystolicPressure"));
//            System.out.println(ars.getString("InsuranceNumber"));
//            System.out.println(ars.getString("Name"));
//            System.out.println(ars.getString("Sex"));
//            System.out.println(ars.getString("Age"));
//            System.out.println(ars.getString("ApartmentNumber"));
//            System.out.println(ars.getString("DiastolicPressure"));
//            System.out.println(ars.getString("Community"));
//            System.out.println(ars.getString("City"));
            }
            con.close();
        } catch (SQLException ex) {
            Logger.getLogger(communityJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void maxiumAgejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_maxiumAgejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_maxiumAgejTextFieldActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> communityjComboBox;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField maxiumAgejTextField;
    private javax.swing.JTextField minimumAgejTextField;
    private javax.swing.JButton searchjButton;
    // End of variables declaration//GEN-END:variables
}