/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import model.jdbcConnection;
import java.sql.Connection;
import model.Person;
import model.peopleStore;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
/**
 *
 * @author ABHI
 */
public class CreatePersonPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreatePersonPanel
     */
    public CreatePersonPanel() {
        initComponents();
        displayInfo();
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        personNamejLabel = new javax.swing.JLabel();
        AgejLabel = new javax.swing.JLabel();
        sexjLabel = new javax.swing.JLabel();
        apartmentNumberjLabel = new javax.swing.JLabel();
        communityJLabel = new javax.swing.JLabel();
        cityJLabel = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        agejTextField = new javax.swing.JTextField();
        apartmentNumberjTextField = new javax.swing.JTextField();
        communityjTextField = new javax.swing.JTextField();
        cityjTextField = new javax.swing.JTextField();
        sexjComboBox = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        CreatejButton = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setBackground(new java.awt.Color(0, 204, 255));

        personNamejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        personNamejLabel.setText("Person Name");

        AgejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgejLabel.setText("Age");

        sexjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexjLabel.setText("Sex");

        apartmentNumberjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apartmentNumberjLabel.setText("Apartment Number");

        communityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        communityJLabel.setText("Community");

        cityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cityJLabel.setText("City");

        agejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextFieldActionPerformed(evt);
            }
        });

        sexjComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "F", "M", "Others" }));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("CREATE PERSON");

        CreatejButton.setText("Create");
        CreatejButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CreatejButtonActionPerformed(evt);
            }
        });

        jTable1.setBackground(new java.awt.Color(0, 204, 255));
        jTable1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insurance Number", "Name", "Age", "Sex", "Apartment Number", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(communityJLabel)
                                    .addComponent(apartmentNumberjLabel)
                                    .addComponent(sexjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(52, 52, 52)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(AgejLabel)
                                    .addComponent(personNamejLabel))))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(sexjComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(apartmentNumberjTextField)
                                    .addComponent(communityjTextField)
                                    .addComponent(cityjTextField))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 146, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 774, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(124, 124, 124)
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 182, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(149, 149, 149)
                                .addComponent(CreatejButton)))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(19, 19, 19)
                                .addComponent(jLabel1)
                                .addGap(85, 85, 85))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(personNamejLabel)
                                    .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(23, 23, 23)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(AgejLabel)
                            .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(23, 23, 23)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexjLabel)
                            .addComponent(sexjComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(apartmentNumberjLabel)
                            .addComponent(apartmentNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(communityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityJLabel))
                        .addGap(34, 34, 34)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityJLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(CreatejButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(61, 61, 61)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(174, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextFieldActionPerformed

    private void CreatejButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CreatejButtonActionPerformed
        // TODO add your handling code here:
        jdbcConnection obj = new jdbcConnection();
        Connection con= obj.connect();
       String mess = nullcheckfn();
       if(mess!=null)
       {
       JOptionPane.showMessageDialog(this,mess);
       }
       else
       {
       DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
                model.setRowCount(0);
                Object[] row = new Object[7];
            String insuranceNo = obj.createPerson(con,NamejTextField.getText(),Integer.parseInt(agejTextField.getText()),sexjComboBox.getSelectedItem().toString(),apartmentNumberjTextField.getText(),communityjTextField.getText(),cityjTextField.getText());
            row[0] = insuranceNo;
            row[1] = NamejTextField.getText();
            row[2] = Integer.parseInt(agejTextField.getText());
            row[3] = sexjComboBox.getSelectedItem().toString();
            row[4] = apartmentNumberjTextField.getText();
            row[5] = communityjTextField.getText();
            row[6] = cityjTextField.getText();
            model.addRow(row);
            if(con!=null)
            { try {
                con.close();
            } catch (SQLException ex) {
                Logger.getLogger(CreatePersonPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            displayInfo();
       }
    }//GEN-LAST:event_CreatejButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgejLabel;
    private javax.swing.JButton CreatejButton;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JLabel apartmentNumberjLabel;
    private javax.swing.JTextField apartmentNumberjTextField;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JLabel communityJLabel;
    private javax.swing.JTextField communityjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel personNamejLabel;
    private javax.swing.JComboBox<String> sexjComboBox;
    private javax.swing.JLabel sexjLabel;
    // End of variables declaration//GEN-END:variables

    private void displayInfo() {
     
    try 
    {
            jdbcConnection obj = new jdbcConnection();
            Connection con= obj.connect();
            //obj.displaypersonInformation(con);
          //  System.out.println(sexjComboBox.getName());
            
            ResultSet rs = obj.displaypersonInformation(con);
            peopleStore pstore = new peopleStore();
            while(rs.next()!=false)
            {   Person newperson = new Person();
                newperson.setInsuranceNumber(rs.getString("InsuranceNumber"));
                newperson.setName(rs.getString("Name"));
                newperson.setSex(rs.getString("sex"));
                newperson.setAge(rs.getInt("Age"));
                newperson.setApartmentNumber(rs.getString("ApartmentNumber"));
                newperson.setCommunity(rs.getString("Community"));
                newperson.setCity(rs.getString("City"));
                pstore.addperson(newperson);
            }
           DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
          Object[] row = new Object[7];
           
            for(Person p:pstore.getPeopleDb())
            { System.out.println(p.getInsuranceNumber());
              System.out.println("!!!!!!!!!!!!!!!!");  
              row[0] =p.getInsuranceNumber();
              row[1] = p.getName();
              row[2] = p.getAge();
              row[3] = p.getSex();
              row[4] = p.getApartmentNumber();
              row[5] = p.getCommunity();
              row[6] = p.getCity();
              model.addRow(row);
              
            }
    }
    catch(SQLException e)
    {   System.out.println(e);
    }   
    }
    
    public String nullcheckfn()
    {   String boolval = null;
        if(NamejTextField.getText().isEmpty()==true)
        { boolval = "Please enter a valid name";
        }
        else if(NamejTextField.getText().matches("[a-zA-Z]+")==false)
                {       boolval="Name cannot contain letters";
                } 
       
        else if(agejTextField.getText().isEmpty()==true)
            
        {
            boolval="Age cannot be blank";
                }
        else if(agejTextField.getText().matches("[a-zA-Z]+")==true)
        { boolval = "Age cannot contain letters";
        }
        else if(agejTextField.getText().matches("[a-zA-Z]+")!=true)
        { 
            if(Integer.parseInt(agejTextField.getText())>150)
            {
                boolval = "The Age cannot be greater than 150";
            }
            
        }
        
        if(apartmentNumberjTextField.getText().isEmpty()==true)
        { boolval = "Apartment number cannot be empty";
        }
        
        else if(communityjTextField.getText().isEmpty()==true)
        { boolval = "Community is a required field";
        }
        
        else if(communityjTextField.getText().matches("[a-zA-Z]+")!=true)
        { boolval = "Enter a valid community without numbers and special characters";
        }
        else if(cityjTextField.getText().isEmpty()==true)
        {
            boolval = "City is a required field";
        }
        else if(cityjTextField.getText().matches("[a-zA-Z]+")!=true)
        {  boolval = "City cannot contain numbers and special characters";
        }
        return boolval;
    }

}
