/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JButton;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.jdbcConnection;
import javax.swing.DefaultComboBoxModel;
/**
 *
 * @author ABHI
 */
public class PatientJPanel extends javax.swing.JPanel {

    /**
     * Creates new form PatientJPanel
     */
    public PatientJPanel() {
        initComponents();
        try {
            updateJTable2();
 
//            communityjComboBox.setMo
//            communityjComboBox.setModel(community);
        } catch (SQLException ex) {
            Logger.getLogger(PatientJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        jPanel1.setVisible(false);
        addPatientjPanel.setVisible(false);
        
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        searchjTextField = new javax.swing.JTextField();
        searchjButton = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        patientNamejLabel = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        AgejLabel = new javax.swing.JLabel();
        agejTextField = new javax.swing.JTextField();
        sexjLabel = new javax.swing.JLabel();
        SexjTextField = new javax.swing.JTextField();
        apartmentNumberjLabel = new javax.swing.JLabel();
        apartmentNumberjTextField = new javax.swing.JTextField();
        communityJLabel = new javax.swing.JLabel();
        communityjTextField = new javax.swing.JTextField();
        cityJLabel = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        addjButton = new javax.swing.JButton();
        enterSystolicjLabel = new javax.swing.JLabel();
        newSystolicjTextField = new javax.swing.JTextField();
        enterDiastolicjLabel1 = new javax.swing.JLabel();
        newDiastolicjTextField1 = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        addPatientjPanel = new javax.swing.JPanel();
        patientNamejLabel1 = new javax.swing.JLabel();
        NamejTextField1 = new javax.swing.JTextField();
        apartmentNumberjLabel1 = new javax.swing.JLabel();
        apartmentNumberjTextField1 = new javax.swing.JTextField();
        communityJLabel1 = new javax.swing.JLabel();
        communityjTextField1 = new javax.swing.JTextField();
        cityJLabel1 = new javax.swing.JLabel();
        cityjTextField1 = new javax.swing.JTextField();
        sexjLabel1 = new javax.swing.JLabel();
        SexjTextField1 = new javax.swing.JTextField();
        AgejLabel1 = new javax.swing.JLabel();
        agejTextField1 = new javax.swing.JTextField();
        SystolicjLabel2 = new javax.swing.JLabel();
        SystolicjTextField = new javax.swing.JTextField();
        DiastolicjLabel = new javax.swing.JLabel();
        DiastolicjTextField = new javax.swing.JTextField();
        addPatientjButton = new javax.swing.JButton();
        InsuranceNumberjLabel = new javax.swing.JLabel();
        insuranceNumberjTextField = new javax.swing.JTextField();
        addNewPatientjButton = new javax.swing.JButton();

        setBackground(new java.awt.Color(0, 204, 255));
        setAutoscrolls(true);
        setPreferredSize(new java.awt.Dimension(800, 800));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Patient Information");

        searchjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjTextFieldActionPerformed(evt);
            }
        });

        searchjButton.setText("Search");
        searchjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchjButtonActionPerformed(evt);
            }
        });

        jPanel1.setBackground(new java.awt.Color(0, 204, 255));

        patientNamejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientNamejLabel.setText("Patient's Name");

        AgejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgejLabel.setText("Age");

        agejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextFieldActionPerformed(evt);
            }
        });

        sexjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexjLabel.setText("Sex");

        SexjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexjTextFieldActionPerformed(evt);
            }
        });

        apartmentNumberjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apartmentNumberjLabel.setText("Apartment Number");

        communityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        communityJLabel.setText("Community");

        cityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cityJLabel.setText("City");

        jTable1.setBackground(new java.awt.Color(0, 204, 255));
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "SystolicPressure", "DiastolicPressure"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        addjButton.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        addjButton.setText("Add Vital");
        addjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addjButtonActionPerformed(evt);
            }
        });

        enterSystolicjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        enterSystolicjLabel.setText("New Systolic Pressure");

        enterDiastolicjLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        enterDiastolicjLabel1.setText("New Diastolic Pressure");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apartmentNumberjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(communityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgejLabel)
                    .addComponent(enterSystolicjLabel)
                    .addComponent(enterDiastolicjLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                    .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apartmentNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(communityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(newSystolicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addjButton)
                    .addComponent(newDiastolicjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addGap(19, 19, 19))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(45, 45, 45)
                .addComponent(patientNamejLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(498, 498, 498))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {NamejTextField, SexjTextField, addjButton, agejTextField, apartmentNumberjTextField, cityjTextField, communityjTextField, newSystolicjTextField});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(patientNamejLabel)
                            .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(26, 26, 26)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apartmentNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(apartmentNumberjLabel))
                        .addGap(30, 30, 30)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(communityJLabel)
                            .addComponent(communityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cityJLabel)
                            .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(38, 38, 38)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(sexjLabel)
                            .addComponent(SexjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(17, 17, 17)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(AgejLabel)
                            .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(27, 27, 27)
                                .addComponent(enterSystolicjLabel))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(newSystolicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(newDiastolicjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(enterDiastolicjLabel1))))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 61, Short.MAX_VALUE)
                .addComponent(addjButton)
                .addGap(16, 16, 16))
        );

        jPanel2.setBackground(new java.awt.Color(0, 204, 255));

        jTable2.setBackground(new java.awt.Color(0, 204, 255));
        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Insurance Number", " Name", "Sex", "Age", "SystolicPressure", "DiastolicPressure", "Community", "City"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jTable2.setShowGrid(true);
        jTable2.setSurrendersFocusOnKeystroke(true);
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 763, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(83, 83, 83)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 157, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(272, Short.MAX_VALUE))
        );

        addPatientjPanel.setBackground(new java.awt.Color(0, 204, 255));

        patientNamejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientNamejLabel1.setText("Patient's Name");

        apartmentNumberjLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apartmentNumberjLabel1.setText("Apartment Number");

        communityJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        communityJLabel1.setText("Community");

        cityJLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cityJLabel1.setText("City");

        sexjLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexjLabel1.setText("Sex");

        SexjTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SexjTextField1ActionPerformed(evt);
            }
        });

        AgejLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgejLabel1.setText("Age");

        agejTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextField1ActionPerformed(evt);
            }
        });

        SystolicjLabel2.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        SystolicjLabel2.setText("Systolic Pressure");

        SystolicjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SystolicjTextFieldActionPerformed(evt);
            }
        });

        DiastolicjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        DiastolicjLabel.setText("Diastolic Pressure");

        DiastolicjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                DiastolicjTextFieldActionPerformed(evt);
            }
        });

        addPatientjButton.setText("Add Patient");
        addPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPatientjButtonActionPerformed(evt);
            }
        });

        InsuranceNumberjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        InsuranceNumberjLabel.setText("Insurance Number");

        insuranceNumberjTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insuranceNumberjTextFieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout addPatientjPanelLayout = new javax.swing.GroupLayout(addPatientjPanel);
        addPatientjPanel.setLayout(addPatientjPanelLayout);
        addPatientjPanelLayout.setHorizontalGroup(
            addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientjPanelLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(InsuranceNumberjLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 190, Short.MAX_VALUE)
                    .addGroup(addPatientjPanelLayout.createSequentialGroup()
                        .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apartmentNumberjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(patientNamejLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cityJLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sexjLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(AgejLabel1)
                            .addComponent(SystolicjLabel2)
                            .addComponent(DiastolicjLabel))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(apartmentNumberjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(NamejTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 122, Short.MAX_VALUE)
                        .addComponent(insuranceNumberjTextField))
                    .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.CENTER)
                        .addComponent(communityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SexjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(agejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(SystolicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(DiastolicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(89, 89, 89))
            .addGroup(addPatientjPanelLayout.createSequentialGroup()
                .addGap(155, 155, 155)
                .addComponent(addPatientjButton)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        addPatientjPanelLayout.setVerticalGroup(
            addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(addPatientjPanelLayout.createSequentialGroup()
                .addGap(6, 6, 6)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(InsuranceNumberjLabel)
                    .addComponent(insuranceNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(13, 13, 13)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(patientNamejLabel1)
                    .addComponent(NamejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(apartmentNumberjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(apartmentNumberjLabel1))
                .addGap(18, 18, 18)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(communityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(communityJLabel1))
                .addGap(18, 18, 18)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cityjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cityJLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SexjTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sexjLabel1))
                .addGap(17, 17, 17)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(agejTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(AgejLabel1))
                .addGap(18, 18, 18)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(SystolicjLabel2)
                    .addComponent(SystolicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(addPatientjPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(DiastolicjLabel)
                    .addComponent(DiastolicjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(addPatientjButton)
                .addContainerGap(152, Short.MAX_VALUE))
        );

        addPatientjPanelLayout.linkSize(javax.swing.SwingConstants.VERTICAL, new java.awt.Component[] {AgejLabel1, DiastolicjLabel, DiastolicjTextField, NamejTextField1, SexjTextField1, SystolicjLabel2, SystolicjTextField, agejTextField1, apartmentNumberjLabel1, apartmentNumberjTextField1, cityJLabel1, cityjTextField1, communityJLabel1, communityjTextField1, patientNamejLabel1, sexjLabel1});

        addNewPatientjButton.setText("Add New Patient");
        addNewPatientjButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addNewPatientjButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(searchjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addPatientjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(searchjButton, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(122, 122, 122)
                        .addComponent(addNewPatientjButton)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 202, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(499, 499, 499))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(86, 86, 86)
                        .addComponent(searchjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(searchjButton)
                            .addComponent(addNewPatientjButton))
                        .addGap(27, 27, 27)
                        .addComponent(addPatientjPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjButtonActionPerformed
        // TODO add your handling code here:
        String insuranceNumberval= insuranceNumbercheck();
        if(insuranceNumberval==null)
        {
        jdbcConnection obj = new jdbcConnection();
//        ArrayList<String> community = new ArrayList<String>();
//        community = obj.neighborhooddropdown();
        String insuranceNumber = searchjTextField.getText();
        
        ResultSet Val = obj.searchPatient(insuranceNumber);
        try {
            System.out.println(Val.getRow());
        } catch (SQLException ex) {
            Logger.getLogger(PatientJPanel.class.getName()).log(Level.SEVERE, null, ex);
        }
        if(Val!=null)
        {   int cat =0;
            try {
            while(Val.next()!=false)
            {   cat++;
                NamejTextField.setText(Val.getString("Name"));
              agejTextField.setText(String.valueOf(Val.getInt("Age")));
              apartmentNumberjTextField.setText(Val.getString("ApartmentNumber"));
              SexjTextField.setText(Val.getString("Sex"));
              communityjTextField.setText(Val.getString("Community"));
              cityjTextField.setText(Val.getString("City"));
              DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
              model.setRowCount(0);
              Object[] row = new Object[2];
              String systolicval = Val.getString("SystolicPressure");
              String diastolicval = Val.getString("DiastolicPressure");
              String [] systolicvital = systolicval.split(",");
              String [] diastolicvital = diastolicval.split(",");
              for(int i=0;i<systolicvital.length;i++)
              {
                String testing1=systolicvital[i];
                String dummy = diastolicvital[i];
                 System.out.println("testingggggg"+testing1);
                System.out.println("testinggggggdias"+dummy);
                row[0] = testing1;
                row[1] = dummy;
                 model.addRow(row);
              }
            }
            
            //updateJTable();
            //searchResultPanel obj1 = new searchResultPanel();
            if(cat>0)
            {
            jPanel1.setVisible(true);
//            DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
//            model.setRowCount(0);
//            Object[] row = new Object[7];
//            ResultSet setResults = obj.displayPatient();
//            while(setResults.next())
//        {   row[0] = setResults.getString("InsuranceNumber");
//            System.out.println(setResults.getString("InsuranceNumber"));   
//            row[1] = setResults.getString("Name");
//              row[2] = setResults.getString("Sex");
//               row[3] = setResults.getInt("Age");
//               row[4] = setResults.getString("Vital");
//               row[5] = setResults.getString("Community");
//              row[6] = setResults.getString("City");
//
//           model.addRow(row);
//        }
               //updateJTable();
           /*  try {
            updateJTable();
        } catch (SQLException ex) {
            Logger.getLogger(PatientJPanel.class.getName()).log(Level.SEVERE, null, ex);
        } */
            }
      else
        {   jPanel1.setVisible(false);
            JOptionPane.showMessageDialog(this, "The patient record is not found");
            String[] options = {"Yes", "No"};
        //Integer[] options = {1, 3, 5, 7, 9, 11};
        //Double[] options = {3.141, 1.618};
        //Character[] options = {'a', 'b', 'c', 'd'};
        int x = JOptionPane.showOptionDialog(null, "Do you want to add a patient",
                "Click a button",
                JOptionPane.DEFAULT_OPTION, JOptionPane.INFORMATION_MESSAGE, null, options, options[0]);
            System.out.println(x);
            if(x==0)
            {   searchjTextField.getText();
                addPatientjPanel.setVisible(true);
               String arr[] = obj.onePersonDetail(searchjTextField.getText());
               if(arr.length!=0)
               { //System.out.println(arr[0]);
               insuranceNumberjTextField.setText(arr[0]);
               NamejTextField1.setText(arr[1]);
               agejTextField1.setText(arr[2]);
               SexjTextField1.setText(arr[3]);
               apartmentNumberjTextField1.setText(arr[4]);
               communityjTextField1.setText(arr[5]);
               cityjTextField1.setText(arr[6]);
//               NamejTextField1.setText(rs.getString("Name"));
//               apartmentNumberjTextField1.setText(rs.getString("ApartmentNumber"));
//               communityjTextField1.setText(rs.getString("community"));
//               cityjTextField1.setText(rs.getString("City"));
//               SexjTextField1.setText(rs.getString("Sex"));
//               agejTextField1.setText(String.valueOf(rs.getInt("Age")));
//               insuranceNumberjTextField.setText(searchjTextField.getText());
              }
               
               else
               { JOptionPane.showMessageDialog(this, "Add the person in the Person Directory");
               }
            
            }
        }
            
            } catch (SQLException ex) {
                Logger.getLogger(PatientJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            
            
        }
       
     /* ResultSet rs = obj.displayPatient();
      while(rs != null)
      {     try {
          System.out.println(rs.getString("InsuranceNumber"));
          System.out.println("!@#$$$$$$$$$$");
            } catch (SQLException ex) {
                Logger.getLogger(PatientJPanel.class.getName()).log(Level.SEVERE, null, ex);
            }
      } */
        }
else
        { JOptionPane.showMessageDialog(this,insuranceNumberval);
        }
    }//GEN-LAST:event_searchjButtonActionPerformed

    private void searchjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchjTextFieldActionPerformed
        // TODO add your handling code here:
        
        
    }//GEN-LAST:event_searchjTextFieldActionPerformed

    private void agejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextFieldActionPerformed

    private void SexjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexjTextFieldActionPerformed

    private void addjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addjButtonActionPerformed
        // TODO add your handling code here:
        String insuranceNumber = searchjTextField.getText();
        String val = pressuremeasure();
        if(val!=null)
        {JOptionPane.showMessageDialog(this,val);}
        else
        {
        String vitalVal = newSystolicjTextField.getText();
        String diastolicVital = newDiastolicjTextField1.getText();
        String newVital="";
        String newDiastolicVital ="";
        DefaultTableModel updatemodel = (DefaultTableModel) jTable1.getModel();
        for(int i=0;i<updatemodel.getRowCount();i++)
      {  System.out.println(updatemodel.getValueAt(i, 0));
        String local = updatemodel.getValueAt(i, 0).toString();
       newVital = newVital+updatemodel.getValueAt(i, 0)+",";
       
       newDiastolicVital = newDiastolicVital+updatemodel.getValueAt(i, 1)+",";
     
      }
        newVital= newVital+vitalVal;
        newDiastolicVital= newDiastolicVital+diastolicVital;
        //System.out.println(newVital);
        jdbcConnection obj = new jdbcConnection();
        obj.updateVitalCount(insuranceNumber,newVital,newDiastolicVital);
        Object[] row = new Object[2];
        row[0] = vitalVal;
        row[1] = diastolicVital;
        updatemodel.addRow(row);
        DefaultTableModel updatemainmodel = (DefaultTableModel) jTable2.getModel();
        for(int i=0;i<updatemainmodel.getRowCount();i++)
        { String getInsuranceNumber= updatemainmodel.getValueAt(i, 0).toString();
            if(getInsuranceNumber.equals(insuranceNumber))
            { System.out.println(newVital);
             System.out.println(newDiastolicVital);
                updatemainmodel.setValueAt(newVital, i, 4);
                updatemainmodel.setValueAt(newDiastolicVital, i, 5);
                updatemainmodel.fireTableDataChanged();
                break;
               
            }
        
        }
        }
    }//GEN-LAST:event_addjButtonActionPerformed

    private void SexjTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SexjTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SexjTextField1ActionPerformed

    private void agejTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextField1ActionPerformed

    private void SystolicjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SystolicjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_SystolicjTextFieldActionPerformed

    private void DiastolicjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_DiastolicjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_DiastolicjTextFieldActionPerformed

    private void addPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPatientjButtonActionPerformed
        // TODO add your handling code here:
        String val = nullcheckfn();
        if(val==null)
        {
        jdbcConnection obj2 = new jdbcConnection();
        String message = obj2.createPatient(searchjTextField.getText(),SystolicjTextField.getText(),DiastolicjTextField.getText());
        JOptionPane.showMessageDialog(jSplitPane1, message);
        }
        else
        {JOptionPane.showMessageDialog(jSplitPane1, val);
        }
    }//GEN-LAST:event_addPatientjButtonActionPerformed

    private void insuranceNumberjTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insuranceNumberjTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_insuranceNumberjTextFieldActionPerformed

    private void addNewPatientjButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewPatientjButtonActionPerformed
        // TODO add your handling code here:
        addPatientjPanel.setVisible(true);
    }//GEN-LAST:event_addNewPatientjButtonActionPerformed
private javax.swing.JSplitPane jSplitPane1;

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgejLabel;
    private javax.swing.JLabel AgejLabel1;
    private javax.swing.JLabel DiastolicjLabel;
    private javax.swing.JTextField DiastolicjTextField;
    private javax.swing.JLabel InsuranceNumberjLabel;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JTextField NamejTextField1;
    private javax.swing.JTextField SexjTextField;
    private javax.swing.JTextField SexjTextField1;
    private javax.swing.JLabel SystolicjLabel2;
    private javax.swing.JTextField SystolicjTextField;
    private javax.swing.JButton addNewPatientjButton;
    private javax.swing.JButton addPatientjButton;
    private javax.swing.JPanel addPatientjPanel;
    private javax.swing.JButton addjButton;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JTextField agejTextField1;
    private javax.swing.JLabel apartmentNumberjLabel;
    private javax.swing.JLabel apartmentNumberjLabel1;
    private javax.swing.JTextField apartmentNumberjTextField;
    private javax.swing.JTextField apartmentNumberjTextField1;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JLabel cityJLabel1;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JTextField cityjTextField1;
    private javax.swing.JLabel communityJLabel;
    private javax.swing.JLabel communityJLabel1;
    private javax.swing.JTextField communityjTextField;
    private javax.swing.JTextField communityjTextField1;
    private javax.swing.JLabel enterDiastolicjLabel1;
    private javax.swing.JLabel enterSystolicjLabel;
    private javax.swing.JTextField insuranceNumberjTextField;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField newDiastolicjTextField1;
    private javax.swing.JTextField newSystolicjTextField;
    private javax.swing.JLabel patientNamejLabel;
    private javax.swing.JLabel patientNamejLabel1;
    private javax.swing.JButton searchjButton;
    private javax.swing.JTextField searchjTextField;
    private javax.swing.JLabel sexjLabel;
    private javax.swing.JLabel sexjLabel1;
    // End of variables declaration//GEN-END:variables
    private void updateJTable2() throws SQLException
    {
        DefaultTableModel model = (DefaultTableModel) jTable2.getModel();
        model.setRowCount(0);
        Object[] row = new Object[8];
        jdbcConnection obj1 = new jdbcConnection();
        ResultSet setResults = obj1.displayPatient();
     while(setResults.next())
         
     {  //System.out.println(setResults.getString("DiastolicPressure"));
         row[0] = setResults.getString("InsuranceNumber");
        row[1] = setResults.getString("Name"); 
        row[2] = setResults.getString("Sex");
        row[3] = setResults.getInt("Age");
        row[4] = setResults.getString("SystolicPressure");
        row[5] = setResults.getString("DiastolicPressure");
        row[6] = setResults.getString("Community");
        row[7] = setResults.getString("City");
       //row[7] = setResults.getString("City");
        
        model.addRow(row);
     }
     
     
    }
    private void updateJTable1(String insuranceNumber,String updateVital) throws SQLException
    { DefaultTableModel updatemodel = (DefaultTableModel) jTable1.getModel();
    for(int i=0;i<updatemodel.getRowCount();i++)
    {   
    }
    
    }
    public String nullcheckfn()
    {   String boolval = null;
    if(insuranceNumberjTextField.getText().isEmpty()==true)
    { boolval ="Insurance Number cannot be empty";
    }
    else if(insuranceNumberjTextField.getText().matches("\"[a-zA-Z]+\""))
         { boolval="Insurance Number cannot contain letters";
         System.out.println("!@#################");
         }
     
        else if(NamejTextField1.getText().matches("[a-zA-Z]+")==false)
                {       boolval="Name cannot contain letters";
                } 
       
        else if(agejTextField1.getText().isEmpty()==true)
            
        {
            boolval="Age cannot be blank";
                }
        else if(agejTextField1.getText().matches("[a-zA-Z]+")==true)
        { boolval = "Age cannot contain letters";
        }
        else if(agejTextField1.getText().matches("[a-zA-Z]+")!=true)
        { 
            if(Integer.parseInt(agejTextField1.getText())>150)
            {
                boolval = "The Age cannot be greater than 150";
            }
            
        }
        
        if(apartmentNumberjTextField1.getText().isEmpty()==true)
        { boolval = "Apartment number cannot be empty";
        }
        
        else if(communityjTextField1.getText().isEmpty()==true)
        { boolval = "Community is a required field";
        }
        
        else if(communityjTextField1.getText().matches("[a-zA-Z]+")!=true)
        { boolval = "Enter a valid community without numbers and special characters";
        }
        else if(cityjTextField1.getText().isEmpty()==true)
        {
            boolval = "City is a required field";
        }
        else if(cityjTextField1.getText().matches("[a-zA-Z]+")!=true)
        {  boolval = "City cannot contain numbers and special characters";
        }
        try{
        int systolic = Integer.parseInt(SystolicjTextField.getText());
        if(systolic>370)
        { boolval="Enter a valid systolic pressure";
        }
        }
        catch(NumberFormatException e)
        { boolval = "Enter a valid systolic pressure";
        }
        try{
        int diastolic = Integer.parseInt(DiastolicjTextField.getText());
        if(diastolic>360)
        { boolval="Enter a valid Diastolic pressure";
        }
        }
        catch(NumberFormatException e)
        { boolval = "Enter a valid Diastolic pressure";
        }
        return boolval;
    }
    public String insuranceNumbercheck()
    { String val =null;
    System.out.println(searchjTextField.getText());
     if(searchjTextField.getText().isEmpty()==true)
     {  val = "You cannot search with Insurance Number empty";
     }
     else if(searchjTextField.getText().matches("[a-zA-Z]+")==true)
     { val = "Insurance Number cannot contain characters";
     }
    return val;
    }
    public String pressuremeasure()
    { String boolval=null;
     try{
        int systolic = Integer.parseInt(newSystolicjTextField.getText());
        if(systolic>370)
        { boolval="Enter a valid systolic pressure";
        }
        }
        catch(NumberFormatException e)
        { boolval = "Enter a valid systolic pressure";
        }
        try{
        int diastolic = Integer.parseInt(newDiastolicjTextField1.getText());
        if(diastolic>360)
        { boolval="Enter a valid Diastolic pressure";
        }
        }
        catch(NumberFormatException e)
        { boolval = "Enter a valid Diastolic pressure";
        }
        return boolval;
    }

}
