/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ui;

/**
 *
 * @author ABHI
 */
public class searchResultPanel extends javax.swing.JPanel {

    /**
     * Creates new form searchResultPanel
     */
    public searchResultPanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        patientNamejLabel = new javax.swing.JLabel();
        NamejTextField = new javax.swing.JTextField();
        AgejLabel = new javax.swing.JLabel();
        agejTextField = new javax.swing.JTextField();
        sexjLabel = new javax.swing.JLabel();
        apartmentNumberjLabel = new javax.swing.JLabel();
        apartmentNumberjTextField = new javax.swing.JTextField();
        communityJLabel = new javax.swing.JLabel();
        communityjTextField = new javax.swing.JTextField();
        cityJLabel = new javax.swing.JLabel();
        cityjTextField = new javax.swing.JTextField();
        jTextField1 = new javax.swing.JTextField();

        patientNamejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        patientNamejLabel.setText("Patient's Name");

        AgejLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        AgejLabel.setText("Age");

        agejTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                agejTextFieldActionPerformed(evt);
            }
        });

        sexjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        sexjLabel.setText("Sex");

        apartmentNumberjLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        apartmentNumberjLabel.setText("Apartment Number");

        communityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        communityJLabel.setText("Community");

        cityJLabel.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        cityJLabel.setText("City");

        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(211, 211, 211)
                .addComponent(jTextField1)
                .addGap(125, 125, 125))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(53, 53, 53)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(cityJLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 38, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(communityJLabel)
                            .addComponent(apartmentNumberjLabel)
                            .addComponent(sexjLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(26, 26, 26)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(AgejLabel)
                                .addComponent(patientNamejLabel))))
                    .addGap(36, 36, 36)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(agejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 93, Short.MAX_VALUE)
                                    .addGap(29, 29, 29))
                                .addComponent(apartmentNumberjTextField)
                                .addComponent(communityjTextField)
                                .addComponent(cityjTextField))
                            .addGap(23, 23, 23))
                        .addComponent(NamejTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 145, Short.MAX_VALUE))
                    .addGap(54, 54, 54)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(105, 105, 105)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(173, Short.MAX_VALUE))
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(13, 13, 13)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(patientNamejLabel)
                        .addComponent(NamejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(AgejLabel)
                        .addComponent(agejTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(23, 23, 23)
                    .addComponent(sexjLabel)
                    .addGap(31, 31, 31)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(apartmentNumberjLabel)
                        .addComponent(apartmentNumberjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(30, 30, 30)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(communityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(communityJLabel))
                    .addGap(34, 34, 34)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cityjTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(cityJLabel))
                    .addContainerGap(20, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void agejTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_agejTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_agejTextFieldActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AgejLabel;
    private javax.swing.JTextField NamejTextField;
    private javax.swing.JTextField agejTextField;
    private javax.swing.JLabel apartmentNumberjLabel;
    private javax.swing.JTextField apartmentNumberjTextField;
    private javax.swing.JLabel cityJLabel;
    private javax.swing.JTextField cityjTextField;
    private javax.swing.JLabel communityJLabel;
    private javax.swing.JTextField communityjTextField;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JLabel patientNamejLabel;
    private javax.swing.JLabel sexjLabel;
    // End of variables declaration//GEN-END:variables
}
